package pl.biai.gui;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import pl.biai.logic.PossiblePlateDetection;

/**
 *
 * @author Fufer
 * @version 1.0
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Logic class of photo edition algorithms.
     */
    private PossiblePlateDetection pe;

    /**
     * Image converted from Mat object for displaying on the screen. Check
     * overrided method repaint() of guiPhotoPanel.
     */
    private BufferedImage buffImage = null;

    /**
     * Creates new form WindowFrame
     */
    public Gui() {
        initComponents();
        pe = new PossiblePlateDetection();
        //createCroppedTables();
    }

    /**
     * Saves all detected rectangles into one folder.
     */
    public void createCroppedTables() {
        for (int i = 1; i < 120; i++) {
            String path = "C:\\Users\\tomol_000\\Desktop\\snapshots\\foto" + i + ".jpg";
            PossiblePlateDetection.setFilePath(path);
            pe.loadPhotoToMat();
            pe.makeCleanAndSobel();
            pe.makeThresholdAndMorphology();
            pe.findPossiblePlateRects();
            PossiblePlateDetection.testPlateCount++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guiPhotoChooser = new javax.swing.JFileChooser();
        jSplitPane1 = new javax.swing.JSplitPane();
        guiPhotoPanel = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (pe.getBuffImage() != null) {
                    int width = this.getWidth();
                    int x = (this.getWidth() - pe.getBuffImage().getWidth(null)) / 2;
                    int y = (this.getHeight() - pe.getBuffImage().getHeight(null)) / 2;
                    g.drawImage(pe.getBuffImage(), x, y, this);
                }
            }
        };
        guiOptionsPanel = new javax.swing.JPanel();
        greyAndNoiseRemoveButon = new javax.swing.JButton();
        threshAndMorphButton = new javax.swing.JButton();
        detectRectsButton = new javax.swing.JButton();
        xmlTestButton = new javax.swing.JButton();
        guiMenuBar = new javax.swing.JMenuBar();
        guiFirstMenu = new javax.swing.JMenu();
        guiFirstMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        guiPhotoChooser.setCurrentDirectory(new java.io.File("C:\\Users\\tomol_000\\Desktop"));
        guiPhotoChooser.setDialogTitle("Wybierz zdjęcie");
        guiPhotoChooser.setFileFilter(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Automatic Plate Recognition System");
        setMinimumSize(new java.awt.Dimension(800, 820));

        jSplitPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Plate photography"));
        jSplitPane1.setDividerLocation(600);
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        guiPhotoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        guiPhotoPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        guiPhotoPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout guiPhotoPanelLayout = new javax.swing.GroupLayout(guiPhotoPanel);
        guiPhotoPanel.setLayout(guiPhotoPanelLayout);
        guiPhotoPanelLayout.setHorizontalGroup(
            guiPhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1016, Short.MAX_VALUE)
        );
        guiPhotoPanelLayout.setVerticalGroup(
            guiPhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        jSplitPane1.setTopComponent(guiPhotoPanel);

        guiOptionsPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        guiOptionsPanel.setMinimumSize(new java.awt.Dimension(800, 200));
        guiOptionsPanel.setPreferredSize(new java.awt.Dimension(800, 200));
        guiOptionsPanel.setRequestFocusEnabled(false);

        greyAndNoiseRemoveButon.setText("Usuń szumy + szarość");
        greyAndNoiseRemoveButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greyAndNoiseRemoveButonActionPerformed(evt);
            }
        });

        threshAndMorphButton.setText("Progowanie i morph");
        threshAndMorphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threshAndMorphButtonActionPerformed(evt);
            }
        });

        detectRectsButton.setText("Wykryj prostokąty");
        detectRectsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detectRectsButtonActionPerformed(evt);
            }
        });

        xmlTestButton.setText("XML test");
        xmlTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xmlTestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout guiOptionsPanelLayout = new javax.swing.GroupLayout(guiOptionsPanel);
        guiOptionsPanel.setLayout(guiOptionsPanelLayout);
        guiOptionsPanelLayout.setHorizontalGroup(
            guiOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiOptionsPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(greyAndNoiseRemoveButon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(threshAndMorphButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detectRectsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(xmlTestButton)
                .addContainerGap())
        );
        guiOptionsPanelLayout.setVerticalGroup(
            guiOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guiOptionsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(guiOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greyAndNoiseRemoveButon)
                    .addComponent(threshAndMorphButton)
                    .addComponent(detectRectsButton)
                    .addComponent(xmlTestButton))
                .addGap(36, 36, 36))
        );

        jSplitPane1.setBottomComponent(guiOptionsPanel);

        guiFirstMenu.setText("Plik");

        guiFirstMenuItem1.setText("Wczytaj zdjęcie");
        guiFirstMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiFirstMenuItem1ActionPerformed(evt);
            }
        });
        guiFirstMenu.add(guiFirstMenuItem1);

        guiMenuBar.add(guiFirstMenu);

        jMenu2.setText("Edit");
        guiMenuBar.add(jMenu2);

        setJMenuBar(guiMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guiFirstMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiFirstMenuItem1ActionPerformed
        //Sciezka domyslna ustawiona bo mi sie ciagle ladowac obrazku 
        //nie chcialo, poniższy kod otwiera file selectora i wybierasz zdjęcie
        /*
         guiPhotoChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
         guiPhotoChooser.showOpenDialog(null);
         guiPhotoChooser.setVisible(true);
         File selectedFile = guiPhotoChooser.getSelectedFile();
        
         PossiblePlateDetection.setFilePath(guiPhotoChooser.getSelectedFile().getAbsolutePath());
         */

        String path = "C:\\Users\\tomol_000\\Desktop\\ANRP\\src\\resources\\test3.jpg";
        //String path = "C:\\Users\\tomol_000\\Desktop\\ANRP BIAI Project\\ANRP\\src\\resources\\test3.jpg";
        PossiblePlateDetection.setFilePath(path);

        pe.loadPhotoToMat();
        pe.updatePhoto(false);

        //Maluje fotke w ramce, sprawdz metodę repaint dla guiPhotoPanel.
        repaint();
    }//GEN-LAST:event_guiFirstMenuItem1ActionPerformed

    /**
     * Action when you click first button. Makes photo clean (without noises),
     * gray scale and apply sobel filter. Then it updates photo and repaint it
     * on guiPhotoPanel.
     *
     * @param evt
     */
    private void greyAndNoiseRemoveButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greyAndNoiseRemoveButonActionPerformed
        pe.makeCleanAndSobel();
        pe.updatePhoto(false);
        guiPhotoPanel.repaint();
    }//GEN-LAST:event_greyAndNoiseRemoveButonActionPerformed

    /**
     * Action when you click second button. Makes thresholding and morphology of
     * photo.
     *
     * @param evt
     */
    private void threshAndMorphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threshAndMorphButtonActionPerformed
        pe.makeThresholdAndMorphology();
        pe.updatePhoto(false);
        guiPhotoPanel.repaint();
    }//GEN-LAST:event_threshAndMorphButtonActionPerformed

    /**
     * Action when you click third button. Detects possible rectangles where the
     * plate can be.
     *
     * @param evt
     */
    private void detectRectsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detectRectsButtonActionPerformed
        pe.findPossiblePlateRects();
        pe.updatePhoto(false);
        guiPhotoPanel.repaint();
    }//GEN-LAST:event_detectRectsButtonActionPerformed

    private void xmlTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xmlTestButtonActionPerformed
        pe.filterPossiblePlates();
    }//GEN-LAST:event_xmlTestButtonActionPerformed

    /**
     * Creates GUI of application.
     */
    public void createGui() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton detectRectsButton;
    private javax.swing.JButton greyAndNoiseRemoveButon;
    private javax.swing.JMenu guiFirstMenu;
    private javax.swing.JMenuItem guiFirstMenuItem1;
    private javax.swing.JMenuBar guiMenuBar;
    private javax.swing.JPanel guiOptionsPanel;
    private javax.swing.JFileChooser guiPhotoChooser;
    private javax.swing.JPanel guiPhotoPanel;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton threshAndMorphButton;
    private javax.swing.JButton xmlTestButton;
    // End of variables declaration//GEN-END:variables
}
